2023-10-22 22:40:40,640 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-22 22:40:40,640 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Configure stats pid to 41216
2023-10-22 22:40:40,640 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Loading settings from /Users/arygup/.config/wandb/settings
2023-10-22 22:40:40,640 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Loading settings from /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/settings
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_init.py:_log_setup():528] Logging user logs to /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/run-20231022_224040-gt3c28jm/logs/debug.log
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/run-20231022_224040-gt3c28jm/logs/debug-internal.log
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_init.py:init():568] calling init triggers
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'activation': 'sigmoid', 'hidden_layer': [10], 'Optimizer': 'SGD'}
2023-10-22 22:40:40,641 INFO    MainThread:41216 [wandb_init.py:init():593] re-initializing run, found existing run on stack: hnmmmxou
2023-10-22 22:40:40,642 INFO    MainThread:41216 [wandb_run.py:_finish():1934] finishing run smaia3/Ques3/hnmmmxou
2023-10-22 22:40:40,642 INFO    MainThread:41216 [jupyter.py:save_history():445] not saving jupyter history
2023-10-22 22:40:40,643 INFO    MainThread:41216 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-22 22:40:40,643 INFO    MainThread:41216 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-22 22:40:40,643 INFO    MainThread:41216 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-22 22:40:40,643 INFO    MainThread:41216 [wandb_run.py:_restore():2151] restore
2023-10-22 22:40:40,643 INFO    MainThread:41216 [wandb_run.py:_restore():2157] restore done
2023-10-22 22:40:43,543 INFO    MainThread:41216 [wandb_init.py:init():618] starting backend
2023-10-22 22:40:43,545 INFO    MainThread:41216 [wandb_init.py:init():622] setting up manager
2023-10-22 22:40:43,547 INFO    MainThread:41216 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-10-22 22:40:43,547 INFO    MainThread:41216 [wandb_init.py:init():628] backend started and connected
2023-10-22 22:40:43,555 INFO    MainThread:41216 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-22 22:40:43,555 INFO    MainThread:41216 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-22 22:40:43,555 INFO    MainThread:41216 [wandb_init.py:init():720] updated telemetry
2023-10-22 22:40:43,571 INFO    MainThread:41216 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
