2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Configure stats pid to 44654
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Loading settings from /Users/arygup/.config/wandb/settings
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Loading settings from /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/settings
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_init.py:_log_setup():528] Logging user logs to /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/run-20231022_234740-lpbtpg8h/logs/debug.log
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/arygup/Documents/GitHub/assignment-3-arygup/A3/wandb/run-20231022_234740-lpbtpg8h/logs/debug-internal.log
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_init.py:init():568] calling init triggers
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'activation': 'tanh', 'hidden_layer': [10], 'Optimizer': 'SGD'}
2023-10-22 23:47:40,423 INFO    MainThread:44654 [wandb_init.py:init():593] re-initializing run, found existing run on stack: eyc1j5ue
2023-10-22 23:47:40,424 INFO    MainThread:44654 [wandb_run.py:_finish():1934] finishing run smaia3/Ques2/eyc1j5ue
2023-10-22 23:47:40,425 INFO    MainThread:44654 [jupyter.py:save_history():445] not saving jupyter history
2023-10-22 23:47:40,425 INFO    MainThread:44654 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-22 23:47:40,425 INFO    MainThread:44654 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-22 23:47:40,425 INFO    MainThread:44654 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-22 23:47:40,425 INFO    MainThread:44654 [wandb_run.py:_restore():2151] restore
2023-10-22 23:47:40,425 INFO    MainThread:44654 [wandb_run.py:_restore():2157] restore done
2023-10-22 23:47:44,802 INFO    MainThread:44654 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2023-10-22 23:47:44,804 INFO    MainThread:44654 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2023-10-22 23:47:44,814 INFO    MainThread:44654 [wandb_run.py:_footer_sync_info():3558] logging synced files
2023-10-22 23:47:44,955 INFO    MainThread:44654 [wandb_init.py:init():618] starting backend
2023-10-22 23:47:44,955 INFO    MainThread:44654 [wandb_init.py:init():622] setting up manager
2023-10-22 23:47:44,958 INFO    MainThread:44654 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-10-22 23:47:44,958 INFO    MainThread:44654 [wandb_init.py:init():628] backend started and connected
2023-10-22 23:47:44,973 INFO    MainThread:44654 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-22 23:47:44,974 INFO    MainThread:44654 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-22 23:47:44,974 INFO    MainThread:44654 [wandb_init.py:init():720] updated telemetry
2023-10-22 23:47:44,996 INFO    MainThread:44654 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-22 23:47:46,673 INFO    MainThread:44654 [wandb_run.py:_on_init():2220] communicating current version
2023-10-22 23:47:46,818 INFO    MainThread:44654 [wandb_run.py:_on_init():2229] got version response 
2023-10-22 23:47:46,818 INFO    MainThread:44654 [wandb_init.py:init():804] starting run threads in backend
2023-10-22 23:47:47,773 WARNING MainThread:44654 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/Users/arygup/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 815, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arygup/anaconda3/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
